// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcpp3qSYQf3guu3R43Xk2aLcUd1kIHWJg',
    appId: '1:136093322261:web:bd74d40a06c421e8c2121c',
    messagingSenderId: '136093322261',
    projectId: 'spark-86d96',
    authDomain: 'spark-86d96.firebaseapp.com',
    storageBucket: 'spark-86d96.appspot.com',
    measurementId: 'G-7NTDHXVXGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq1NvOz1D9XtU354nfs7jVSKiW5DEcTjQ',
    appId: '1:136093322261:android:07ad284eaf58aab6c2121c',
    messagingSenderId: '136093322261',
    projectId: 'spark-86d96',
    storageBucket: 'spark-86d96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxVcyk50-jb8_85jwTf2vs7Xq_soRcTIU',
    appId: '1:136093322261:ios:6a024315269ace08c2121c',
    messagingSenderId: '136093322261',
    projectId: 'spark-86d96',
    storageBucket: 'spark-86d96.appspot.com',
    iosClientId: '136093322261-cdl362vreunst9oi732f2dkep49pcqau.apps.googleusercontent.com',
    iosBundleId: 'com.teamx.spark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxVcyk50-jb8_85jwTf2vs7Xq_soRcTIU',
    appId: '1:136093322261:ios:dc6dc1f012c58b68c2121c',
    messagingSenderId: '136093322261',
    projectId: 'spark-86d96',
    storageBucket: 'spark-86d96.appspot.com',
    iosClientId: '136093322261-i67v5u86mrke63d6jrapghu4qs91dns5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
